name: Discord notifications

on:
  workflow_run:
    workflows: ["PullRequest"]
    types:
      - completed

env:
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  discord:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: on-success
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Github repo: ${{ github.repository }}\n- Branch: ${{ github.event.workflow_run.head_branch }}\n- [Link: to Actions](<${{ github.event.workflow_run.html_url }}>)\n- Status: 🎉  ${{ github.event.workflow_run.conclusion }}  🍏"
      - name: on-failure
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        uses: Ilshidur/action-discord@master
        with:
          args: "Github repo: ${{ github.repository }}\n- Branch: ${{ github.event.workflow_run.head_branch }}\n- [Link: to Actions](<${{ github.event.workflow_run.html_url }}>)\n- Status: 🤔  ${{ github.event.workflow_run.conclusion }}  💣💥"
