name: PublishRelease

on:
  push:
    tags:
      - "*"

jobs:
  release:
    name: publish-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --config .goreleaser-actions.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          PUBLISH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          CHOCOKEY: ${{ secrets.CHOCOKEY }}
          DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
          DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
