on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    name: publish-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          # skip validate because of the hard dependencies on tags and commit hashes.
          args: release --skip-before --skip-validate --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          PUSH_GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          CHOCOKEY: ${{ secrets.CHOCOKEY }}
